### PR TITLE
bug fixed image fixing

### PR DESCRIPTION
**Pull request by carolinevongoc**
# Description

missing image has been remplaced by the placeholder
Capture d’écran 2022-11-20 à 02 22 26

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks Joliflor, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by Joliflor** [comment]
Capture d’écran 2022-11-20 à 02 22 26

**Review by carolinevongoc — COMMENTED** [review]
fixed

**Comment by Joliflor** [comment]
close test

**Comment by Joliflor** [comment]
test

**Comment by Joliflor** [comment]
t

**Review by vanessa-cooper — APPROVED** [review]
Excellent job Joliflor! You're now able to merge the PR.

**Pull request merged**
